name: control_financiero
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Persistencia de Datos (SQLite)
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.20

  # Gestión de Estado y Sesión
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Formateo de Monedas y Fechas
  intl: ^0.19.0

  # Estadísticas y Gráficos
  fl_chart: ^0.66.0

  # Fuentes y Estilo
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/